#####################################################################
# Copyright (c) 2023, Oracle and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#####################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{{app_name}}}
  labels:
    app: {{{app_name}}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{{app_name}}}
  template:
    metadata:
      labels:
        app: {{{app_name}}}
    spec:
      containers:
      - name: {{{app_name}}}
        imagePullPolicy: Always
        image: {{{image_name}}}
        ports:
          - containerPort: 8080
      imagePullSecrets:
      - name: {{{secret_name}}}
